name: workflow-for-testing
on: [push]
jobs:
  automerging_pool_requests:
    name: test-job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2

      - name: print
        run: echo '${{ github.actor }}'