name: workflow-for-testing
on: [push]
  jobs:
    automerging_pool_requests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        -name: print
         run: echo '${{ github.actor }}'