name: workflow-for-testing
on:
  push:
    branches: [main]

jobs:
  automerging_pool_requests:
    if: github.actor == 'jskripnik'
    name: test-job
    runs-on: ubuntu-20.04
    steps:
      - name: print
        shell: bash
        run: |
          echo 'Hello world! ' ${{ github.actor }}
