name: workflow-for-testing
on:
  push:
    branches: [main]

jobs:
  automerging_pool_requests:
    name: test-job
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
      - uses: actions/checkout@v2

      - name: print
        shell: bash
        run: |
          echo ${{ github.actor }}